FROM centos-nova-base:7

# Install updates, requirements, and clean up
RUN yum update -y && yum install -y php http && yum clean all

# This is mostly a hint to docker and only works if you use -P.
# Really you should be using -p 8080:8080 when testing with docker.
EXPOSE 8080

CMD /usr/libexec/tomcat/server start
