#Start with the official tomcat container with debian slim, tomcat 9, jre 8
FROM tomcat:9-jre8-slim

#Remove default app
RUN rm -rf  /usr/local/tomcat/webapps/ROOT \
  /usr/local/tomcat/examples\
  /usr/local/tomcat/docs \
  /usr/local/tomcat/ROOT



