#Start with the official tomcat container
FROM tomcat:8-slim

#Remove default app
RUN rm -rf  /usr/local/tomcat/webapps/ROOT \
  /usr/local/tomcat/examples\
  /usr/local/tomcat/docs \
  /usr/local/tomcat/ROOT



